### ISSUE TITLE
comScore class name not respecting Java coding conventions

### ISSUE THREAD

**Issue by kleinsenberg** [Pmovil/comScore#1]
Class names should be nouns, in mixed case with the first letter of each internal word _capitalised_. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

From: http://www.oracle.com/technetwork/java/codeconventions-135099.html

**Comment by FabricioCabeca** [comment]
It uses the same convention of the original library, it sucks, but I've decided to keep my port aligned with it for the sake of simplicity. See https://github.com/Pmovil/comScore/blob/master/native/android/com/pmovil/comscore/NativeComScoreImpl.java
