### ISSUE TITLE
Google Play warning: You are using an unsafe implementation of X509TrustManager

### ISSUE THREAD

**Issue by yaniv-investing** [Pmovil/comScore#2]
Your app(s) listed at the end of this email use an unsafe implementation of the interface X509TrustManager. Specifically, the implementation ignores all SSL certificate validation errors when establishing an HTTPS connection to a remote host, thereby making your app vulnerable to man-in-the-middle attacks. An attacker could read transmitted data (such as login credentials) and even change the data transmitted on the HTTPS connection. If you have more than 20 affected apps in your account, please check the Developer Console for a full list.

Affected app(s), version(s), and class(es):
104 
com.comscore.utils.b;

**Comment by FabricioCabeca** [comment]
Thanks for reporting this, it is an issue with the closed source comScore library, so it must be fixed by them.
